name: "Build"
description: "Builds package using Hatch and uploads to github artifact"
inputs:
  dist-artifact-name:
    description: "Name of GitHub artifact that contains the built package after building (Wheel & SDist)"
    required: true
    default: "dist"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6

    - run: uv build
      shell: sh

    - name: Upload Built Artifacts (Wheel & SDist)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.dist-artifact-name }}
        path: dist/*
