name: "Build"
description: "Builds package using Hatch and uploads to github artifact"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.13"
  dist-artifact-name:
    description: "Name of GitHub artifact that contains the built package after building (Wheel & SDist)"
    required: true
    default: "dist"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: pip install hatch
      shell: sh

    - name: Build Package
      run: hatch build
      shell: sh

    - name: Upload Built Artifacts (Wheel & SDist)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.dist-artifact-name }}
        path: dist/*
