site_name: Context Menu Python Toolkit
nav:
  - Home:
    - index.md
  - Context Menu:
    - context_menu/context_menu.md
  - Context Menu Bindings:
    - context_menu_bindings/bindings.md
    - context_menu_bindings/access_scope.md
    - context_menu_bindings/menu_item_type.md
  - Features:
    - features/ifeature.md
    - features/display_text.md
    - features/command.md
    - features/icon.md
    - features/shift_click.md
    - features/separator.md
    - features/position.md
    - features/selection_model.md
    - features/has_lua_shield.md
    - features/disabled.md
    - features/no_working_directory.md
    - features/note.md
  - Registry Structs:
    - registry_structures/registry_path.md
    - registry_structures/registry_key.md
    - registry_structures/registry_value.md

watch:
  - context_menu_toolkit
  - docs/
  - mkdocs.yml

theme:
  name: 'material'
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - navigation.indexes
    - content.code.annotate
    - content.footnote.tooltips
    - toc:
        permalink: true
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - toc:
      permalink: "¶"
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets  # allows --8<--
  - pymdownx.details  # allows ??? note, warn, success
  - pymdownx.superfences: # ```python {linenums="1"}
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
- search
- panzoom:
    always_show_hint: true
    full_screen: true
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        inventories:
          - url: https://docs.python.org/3/objects.inv
            domains: [ py, std ]
        options:
          members_order: source
          separate_signature: true
          filters: [ "!^_" ]
          docstring_options:
            heading_level: 2
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
          show_root_heading: true
          show_root_full_path: false
          show_root_toc_entry: false

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
