name: "Linting"
description: "Lints project using Ruff."

inputs:
  python-version:
    description: "The Python version to use."
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install lint dependencies
      run: uv sync --group lint
      shell: sh

    - run: uv run ruff check
      shell: sh
