name: "Type Checking"
description: "Perform type checking using Mypy and Pyright"

inputs:
  python-version:
    description: "The Python version to use."
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install typechecking dependencies
      run: uv sync --group typechecking
      shell: sh

    - run: uv run mypy
      shell: sh

    - run: uv run pyright
      shell: sh
