name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    name: Lint
    runs-on: windows-2025
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Lint
        uses: ./.github/actions/lint
        with:
          python-version: ${{ matrix.python-version }}

  typechecking:
    name: Typechecking
    runs-on: windows-2025
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Typechecking
        uses: ./.github/actions/typechecking
        with:
          python-version: ${{ matrix.python-version }}

  test:
    name: Test
    runs-on: windows-2025
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build
        uses: ./.github/actions/build-package

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: lint
    if: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docs
        uses: ./.github/actions/build-docs
