name: CI/CD Pipeline

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: windows-2025 # winreg module is not available on linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - uses: astral-sh/setup-uv@v10.0.1

      - name: Install lint dependencies
        run: uv sync --group lint
        shell: sh

      - run: uv run ruff check
        shell: sh

      - run: uv run ruff format --diff .
        shell: sh

  typechecking:
    name: Typechecking
    runs-on: windows-2025 # winreg module is not available on linux
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install typechecking dependencies
        run: uv sync --group typechecking
        shell: sh

      - run: uv run mypy
        shell: sh

      - run: uv run pyright
        shell: sh

  test:
    name: Test
    runs-on: windows-2025 # winreg module is not available on linux
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: uv sync --group test
        shell: sh

      - run: uv run pytest
        shell: sh

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Build
        uses: ./.github/actions/build-package

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Build Docs
        uses: ./.github/actions/build-docs
