# This workflow creates a new version of the package. Can be used for both dev and prod.
# Package version is determined from pyproject.toml.
# Triggered on pushes/merges to master and can be triggered automatically
name: Create new package version

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint

  typechecking:
    name: Typechecking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Typechecking
        uses: ./.github/actions/typechecking

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - typechecking

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-package

  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write  # mandatory for Trusted Publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
          verbose: 'true'

  create_github_release:
    name: Create tag & release
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Download artifacts (Wheel & SDist)
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Get package version
        run: |
          pip install toml-cli
          VERSION=$(toml get --toml-path pyproject.toml project.version)
          echo "::notice::Package Version: $VERSION"
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $VERSION \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} $VERSION" \
              --generate-notes

      - name: Upload dists to release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $VERSION dist/*

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - typechecking

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docs
        uses: ./.github/actions/build-docs

  deploy_docs_gh_pages:
    name: Deploy docs to GitHub pages
    runs-on: ubuntu-latest
    needs:
      - build_docs
    if: github.ref_name == 'master'

    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'

    steps:
      - name: "Download static files from build_docs stage"
        uses: actions/download-artifact@v4
        with:
          name: 'site-files'
          path: site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
