# ran when new version should be created and deployed
on:
  push:
    branches:
      - 'feature/docs'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/test
